[package]
name = "hexbait-common"
version = "0.1.0"
edition = "2024"

[dependencies]
positioned-io = { version = "0.3.5", default-features = false }
memmap2 = { version = "0.9.9", default-features = false }
